# Generated by Django 4.2.5 on 2023-10-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True, default='https://icons8.com/icon/j1UxMbqzPi7n/no-image', null=True),
        ),
    ]
